# Generated by Django 5.0.7 on 2024-08-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blogpost_blogpostimage_blogpost_featured_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='latest_image',
            new_name='main_image',
        ),
    ]
