# Generated by Django 5.0.7 on 2024-08-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_blogpost_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='main_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
