# Generated by Django 5.0.7 on 2024-08-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_alter_blogpost_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
    ]
