# Generated by Django 5.0.7 on 2024-08-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_destination_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='is_featured_destination',
        ),
        migrations.AddField(
            model_name='destination',
            name='is_featured_destination',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='main_image',
            field=models.ImageField(upload_to='blog_images/'),
        ),
    ]
