# Generated by Django 5.0.7 on 2024-08-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_emailnewsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnewsletter',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
